import { PERMISSIONS } from "./permissions.js";

export const ROLES = {
  EMPLOYEE: [],
  ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.CREATE_FOOD,
    PERMISSIONS.UPDATE_FOOD,
    PERMISSIONS.DELETE_FOOD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.SELL_FOOD,
  ],

  MANAGER: [
    PERMISSIONS.CREATE_FOOD,
    PERMISSIONS.UPDATE_FOOD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.UPDATE_INVENTORY,
  ],

  CASHIER: [
    PERMISSIONS.SELL_FOOD,
  ],

  INVENTORY: [
    PERMISSIONS.UPDATE_INVENTORY,
  ],
};